create table if not exists public.customers (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  mobile text not null,
  address text default '',
  gov_id text default '',
  principal numeric(14, 2) not null default 0,
  interest_rate numeric(8, 3) not null default 0,
  loan_date date not null default current_date,
  collateral text default '',
  gold_weight numeric(10, 3) not null default 0,
  notes text default '',
  created_at timestamptz not null default now()
);

create table if not exists public.payments (
  id bigint generated by default as identity primary key,
  customer_id bigint not null references public.customers(id) on delete cascade,
  payment_date date not null default current_date,
  total_paid numeric(14, 2) not null default 0,
  interest_paid numeric(14, 2) not null default 0,
  principal_paid numeric(14, 2) not null default 0,
  remaining_principal numeric(14, 2) not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists customers_user_id_idx on public.customers(user_id);
create index if not exists payments_customer_id_idx on public.payments(customer_id);

alter table public.customers enable row level security;
alter table public.payments enable row level security;

drop policy if exists "Users can view their customers" on public.customers;
create policy "Users can view their customers"
  on public.customers for select
  using (auth.uid() = user_id);

drop policy if exists "Users can insert their customers" on public.customers;
create policy "Users can insert their customers"
  on public.customers for insert
  with check (auth.uid() = user_id);

drop policy if exists "Users can update their customers" on public.customers;
create policy "Users can update their customers"
  on public.customers for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "Users can delete their customers" on public.customers;
create policy "Users can delete their customers"
  on public.customers for delete
  using (auth.uid() = user_id);

drop policy if exists "Users can view their payments" on public.payments;
create policy "Users can view their payments"
  on public.payments for select
  using (exists (
    select 1 from public.customers
    where customers.id = payments.customer_id
      and customers.user_id = auth.uid()
  ));

drop policy if exists "Users can insert their payments" on public.payments;
create policy "Users can insert their payments"
  on public.payments for insert
  with check (exists (
    select 1 from public.customers
    where customers.id = payments.customer_id
      and customers.user_id = auth.uid()
  ));
