create table if not exists public.customers (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  mobile text not null,
  address text default '',
  gov_id text default '',
  principal numeric(14, 2) not null default 0,
  interest_rate numeric(8, 3) not null default 0,
  interest_type text not null default 'SIMPLE' check (interest_type in ('SIMPLE', 'COMPOUND')),
  interest_carry numeric(14, 2) not null default 0,
  interest_paid_since_loan_date numeric(14, 2) not null default 0,
  last_advance_amount numeric(14, 2),
  last_advance_date date,
  loan_date date not null default current_date,
  collateral text default '',
  gold_weight numeric(10, 3) not null default 0,
  notes text default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.customers add column if not exists interest_type text not null default 'SIMPLE';
alter table public.customers add column if not exists interest_carry numeric(14, 2) not null default 0;
alter table public.customers add column if not exists interest_paid_since_loan_date numeric(14, 2) not null default 0;
alter table public.customers add column if not exists last_advance_amount numeric(14, 2);
alter table public.customers add column if not exists last_advance_date date;
alter table public.customers add column if not exists updated_at timestamptz not null default now();
alter table public.customers drop constraint if exists customers_interest_type_check;
alter table public.customers add constraint customers_interest_type_check check (interest_type in ('SIMPLE', 'COMPOUND'));

create table if not exists public.payments (
  id bigint generated by default as identity primary key,
  customer_id bigint not null references public.customers(id) on delete cascade,
  payment_date date not null default current_date,
  total_paid numeric(14, 2) not null default 0,
  interest_paid numeric(14, 2) not null default 0,
  principal_paid numeric(14, 2) not null default 0,
  remaining_principal numeric(14, 2) not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists customers_user_id_idx on public.customers(user_id);
create index if not exists payments_customer_id_idx on public.payments(customer_id);

alter table public.customers enable row level security;
alter table public.payments enable row level security;

drop policy if exists "Users can view their customers" on public.customers;
create policy "Users can view their customers"
  on public.customers for select
  using (auth.uid() = user_id);

drop policy if exists "Users can insert their customers" on public.customers;
create policy "Users can insert their customers"
  on public.customers for insert
  with check (auth.uid() = user_id);

drop policy if exists "Users can update their customers" on public.customers;
create policy "Users can update their customers"
  on public.customers for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "Users can delete their customers" on public.customers;
create policy "Users can delete their customers"
  on public.customers for delete
  using (auth.uid() = user_id);

drop policy if exists "Users can view their payments" on public.payments;
create policy "Users can view their payments"
  on public.payments for select
  using (exists (
    select 1 from public.customers
    where customers.id = payments.customer_id
      and customers.user_id = auth.uid()
  ));

drop policy if exists "Users can insert their payments" on public.payments;
create policy "Users can insert their payments"
  on public.payments for insert
  with check (exists (
    select 1 from public.customers
    where customers.id = payments.customer_id
      and customers.user_id = auth.uid()
  ));

drop policy if exists "Users can update their payments" on public.payments;
create policy "Users can update their payments"
  on public.payments for update
  using (exists (
    select 1 from public.customers
    where customers.id = payments.customer_id
      and customers.user_id = auth.uid()
  ))
  with check (exists (
    select 1 from public.customers
    where customers.id = payments.customer_id
      and customers.user_id = auth.uid()
  ));

drop policy if exists "Users can delete their payments" on public.payments;
create policy "Users can delete their payments"
  on public.payments for delete
  using (exists (
    select 1 from public.customers
    where customers.id = payments.customer_id
      and customers.user_id = auth.uid()
  ));

do $$
begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime') then
    if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'customers') then
      execute 'alter publication supabase_realtime add table public.customers';
    end if;
    if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'payments') then
      execute 'alter publication supabase_realtime add table public.payments';
    end if;
  end if;
end $$;

create table if not exists public.subscriptions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null unique references auth.users(id) on delete cascade,
  plan text not null default 'free' check (plan in ('free', 'pro')),
  status text not null default 'active' check (status in ('active', 'expired', 'cancelled', 'payment_failed', 'pending')),
  billing_cycle text check (billing_cycle in ('monthly', 'yearly')),
  start_date timestamptz not null default now(),
  expiry_date timestamptz,
  payment_provider text,
  payment_id text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists subscriptions_user_id_idx on public.subscriptions(user_id);
create index if not exists subscriptions_plan_status_expiry_idx on public.subscriptions(plan, status, expiry_date);

alter table public.subscriptions enable row level security;

drop policy if exists "Users can view their own subscription" on public.subscriptions;
create policy "Users can view their own subscription"
  on public.subscriptions for select
  to authenticated
  using (auth.uid() = user_id);

revoke all on public.subscriptions from anon, authenticated;
grant select on public.subscriptions to authenticated;
grant all on public.subscriptions to service_role;

create or replace function public.create_free_subscription_for_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.subscriptions (user_id, plan, status, start_date)
  values (new.id, 'free', 'active', now())
  on conflict (user_id) do nothing;
  return new;
end;
$$;

revoke all on function public.create_free_subscription_for_new_user() from public, anon, authenticated;

drop trigger if exists on_auth_user_created_subscription on auth.users;
create trigger on_auth_user_created_subscription
  after insert on auth.users
  for each row execute function public.create_free_subscription_for_new_user();

insert into public.subscriptions (user_id, plan, status, start_date)
select users.id, 'free', 'active', now()
from auth.users as users
on conflict (user_id) do nothing;

create or replace function public.update_subscription_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists subscriptions_updated_at on public.subscriptions;
create trigger subscriptions_updated_at
  before update on public.subscriptions
  for each row execute function public.update_subscription_updated_at();

revoke all on function public.update_subscription_updated_at() from public, anon, authenticated;

do $$
begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime')
     and not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'subscriptions') then
    execute 'alter publication supabase_realtime add table public.subscriptions';
  end if;
end $$;
